### ISSUE TITLE
Change needed in URL search pattern regex

### ISSUE THREAD

**Issue by serrc-techops** [uib/autopkg-recipes#2]
In OracleJava8JDK.munki.recipe, additional "[0-9]?" needed in search pattern in order to download current version (Java8JDK-1.8.0_111.dmg as of this writing). 

i.e.
<key>SEARCH_PATTERN</key>
<string>(?P&lt;url&gt;http://download.oracle.com/otn-pub/java/jdk/.*?/jdk-8u[0-9]?[0-9]?[0-9]?-macosx-x64.dmg)</string>

**Comment by askilgl** [comment]
Fixed.
